app1_simbathon5/urls.py
from django.urls import path,include
from .views import *
from app1_simbathon5 import views
app_name = "app1_simbathon5"
urlpatterns = [
    path('', main, name= "main"),
    path('FAQ/', frequentlyaskedquestions , name= "frequentlyaskedquestions"),
    path('<str:id>', views.detail, name="detail"),
    path('book/', book,name="book"),
    path('showmain/',showmain,name="showmain"),
]

project_simbathon5/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1_simbathon5.urls')),
    path('accounts/', include('allauth.urls')),
]

app1_simbathon5/models.py
from django.db import models

# Create your models here.

class FAQ(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length= 200)
    pub_date = models.CharField(max_length = 100)
    body = models.DateTimeField()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[20]

app1_simbathon5/views.py
from django.shortcuts import render,get_object_or_404
from .models import FAQ
# Create your views here.

def showmain(request):
    return render(request, 'app1_simbathon5/index.html')

def frequentlyaskedquestions(request):
    faqs = FAQ.objects.all()
    return render(request, 'app1_simbathon5/FAQ.html',{'faqs':faqs})

def detail(request,id):
    faq = get_object_or_404 (FAQ, pk = id)
    return render(request, 'app1_simbathon5/FAQ.html',{'faq':faq})

def book(request):
    return render(request, 'app1_simbathon5/book.html')
    
def main(request):
    return render(request, 'app1_simbathon5/main.html')

app1_simbathon5/templates/app1_simbathon5/FAQ.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>FAQ 무엇이든 물어보세요</h1> 


<h1>글 목록</h1>

<div>
	{% for faq in faqs %}
	<div>
		<h3>{{faq.title}}</h3>
		{{faq.writer}}<br>
		{{faq.summary}}
        <a href="{%url 'deatil' faq.id %}">...자세히</a>
		<br>
	</div>
	{%endfor%}
</div>

{% endblock %}

app1_simbathon5/templates/app1_simbathon5/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css"
      integrity="sha384-v8BU367qNbs/aIZIxuivaU55N5GPF89WBerHoGA4QTcbUjYiLQtKdrfXnqAcXyTv" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <script src="{% static 'js/data.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>
  <title>Calendar</title>
</head>
<body>
<header>
    <div>
    <a href="{% url 'app1_simbathon5:main'%}">
    <button  type="button" style="background-color: #ffc107; height: 50px; font-weight:900 ;"> 뒤로가기 </button>
    </a>
    </div>
    &nbsp;
    <h1>
    <i class="far fa-calendar-check"></i>
    <span>캘린더</span>
  </h1>
  <div class="calendar_title">
    <button class="prev">&#60;</button>
    <span class="current-year-month"></span>
    <button class="next">&#62;</button>
  </div>
</header>
<section class="content-left">
  <div class="left-main">
    <div class="main-wrap">
      <div class="main-day"></div>
      <div class="main-date"></div>
    </div>
    <div class="todo-wrap">
      <div class="todo-title">예약 목록</div>
      <form class="input-form">
        <input type="text" placeholder="write here!!" class="input-box" />
        <button type="submit" class="input-btn clickBtn">INPUT</button>
      </form>
      <ul class="todoList"></ul>
      <div class="showList">
        <span class="listText"></span>
        <span class="createDate"></span>
        <button class="closed">close</button>
      </div>
      <div class="bgblack"></div>
    </div>
  </div>
</section>
<section class="content-right">
    <div class="day-of-week">
      <div class="dayHeader sun">Sun</div>
      <div class="dayHeader">Mon</div>
      <div class="dayHeader">Tue</div>
      <div class="dayHeader">Wed</div>
      <div class="dayHeader">Thu</div>
      <div class="dayHeader">Fri</div>
      <div class="dayHeader sat">Sat</div>
    </div>
    <div class="calendar-body"></div>
</section>
</body>
</html>

app1_simbathon5/templates/app1_simbathon5/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{faq.title}}</h1> 
작성자: {{faq.writer}}
날짜: {{faq.pub_date}}
<hr>	
<p>{{faq.body}}</p>

{% endblock %}

app1_simbathon5/templates/app1_simbathon5/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css"
      integrity="sha384-v8BU367qNbs/aIZIxuivaU55N5GPF89WBerHoGA4QTcbUjYiLQtKdrfXnqAcXyTv" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <script src="{% static 'js/data.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>
  <title>Calendar</title>
</head>
<body>
<header>
  <h1>
    <i class="far fa-calendar-check"></i>
    <span>캘린더</span>
  </h1>
  <div class="calendar_title">
    <button class="prev">&#60;</button>
    <span class="current-year-month"></span>
    <button class="next">&#62;</button>
  </div>
</header>
<section class="content-left">
  <div class="left-main">
    <div class="main-wrap">
      <div class="main-day"></div>
      <div class="main-date"></div>
    </div>
    <div class="todo-wrap">
      <div class="todo-title">예약 목록</div>
      <form class="input-form">
        <input type="text" placeholder="write here!!" class="input-box" />
        <button type="submit" class="input-btn clickBtn">INPUT</button>
      </form>
      <ul class="todoList"></ul>
      <div class="showList">
        <span class="listText"></span>
        <span class="createDate"></span>
        <button class="closed">close</button>
      </div>
      <div class="bgblack"></div>
    </div>
  </div>
</section>
<section class="content-right">
    <div class="day-of-week">
      <div class="dayHeader sun">Sun</div>
      <div class="dayHeader">Mon</div>
      <div class="dayHeader">Tue</div>
      <div class="dayHeader">Wed</div>
      <div class="dayHeader">Thu</div>
      <div class="dayHeader">Fri</div>
      <div class="dayHeader sat">Sat</div>
    </div>
    <div class="calendar-body"></div>
</section>
</body>
</html>

{% endblock %}

app1_simbathon5/templates/app1_simbathon5/main.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/bg.css' %}">
<title>중앙동아리방 예약 서비스</title>

</head>
<body>
<section> 
    <div class="bg"> 
        <h1>동국대학교 중앙동아리방 예약 서비스</h1> 
        <p>코시국 동아리방을 이용하고 싶다면 로그인 후 예약하자!</p> 
        
        {% if user.is_authenticated %}
        <button type="button"  class="btn"> <a href = "{% url 'app1_simbathon5:book' %}" >예약하기</a></button>
        <button type="button"  class="btn"> <a href ="{% url 'account_logout' %}">Logout</a></button>
        {% else %}
        <button type="button"  class="btn"> <a href = "{% url 'account_login' %}" >login</a></button>
        {% endif %}
    </div>
</section>

</body>
</html>

app1_simbathon5/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css"
        integrity="sha384-v8BU367qNbs/aIZIxuivaU55N5GPF89WBerHoGA4QTcbUjYiLQtKdrfXnqAcXyTv" crossorigin="anonymous">

    <title>동방예약</title>
  </head>
  <body>
    {% include 'shared/_navbar.html' %}
  <div class = "container">
    {% block content %}

    {% endblock %}
  </div>  
</body>
</html>

app1_simbathon5/templates/shared/_navbar.html
<head>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffdf;">
  <a class="navbar-brand" href="{% url 'app1_simbathon5:showmain'%}">동국대 동아리방 예약</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app1_simbathon5:book' %}">캘린더</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1_simbathon5:frequentlyaskedquestions' %}">자주 묻는 질문들</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expended="false">Account</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user.is_authenticated %}
          <li><a class="dropdown-item" href ="{% url 'account_logout' %}">Logout</a></li>
          {% else %}
          <li><a class="dropdown-item" href ="{% url 'account_login' %}">Login</a></li>
          <li><a class="dropdown-item" href ="{% url 'account_signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </li>
    </ul>
  </div>
</nav>
</body>